language: ruby
rvm:
- 2.6.3
dist: trusty
sudo: false
cache: bundler
notifications:
  email: false
install:
- bundle install
script:
- JEKYLL_ENV="production" bundle exec jekyll build
deploy:
  provider: script
  script: bash script/deploy.sh
  skip_cleanup: true
  on:
    tags: true
    branch: staging
branches:
  only:
  - staging
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
env:
  global:
    secure: nS0CbfERp/HjTDpd7Z0FxKoMiAP5iww+VVTHj6EGYbtif9KGYgPReyNCIXnQ7qetL3YL9PPHP2rsrfh6h4+MBIu4qBFsnI/xZeUrUx8QsVFicto3kS7wFY2pFpXxKodiI7ezzV8QInslPmL8+kTmzGJSUSqmUoK1uJKIS3XaWm8KeXe7zsj/aqXwQ7ojvDqLLFDsQNPpq4j8qWw1DzdW1wZwRggOzGZqjFlTVYqfpYfqRFjgUtRB6KUsCrLRurMlF8uL1AbEwGL/j3gQJoBrhl2QE7sKLLI1kJDkGBHj0jIov1gxscot85O8mFfjtYrPpTTfdOdK6UpmHzP1cyYaKGOTjUNTf/S8iq3mOPIYj2XjuvXLkOrecjwn16AYERZrXLwLwONM2x3r53W2LW5JRk6p5RP8HHht6ywDiGLB7kt/my3HO+hIBqGa22g/Zph/MNB4l8v+EoSUcIBuyCmxWD6LvMx4MkVyZTFg3BnWttcihsCGFttGEFighB+fIaXLX3g+qH14Ro2OpU786Ce2JZO991qOENCagPLU2DNGnjNoNkr0tDS8T4xMvrAFS2t2Pu6fyLNy+CB1IgZLHo36t+3hg6t2esKArtbDuMMlQIJ7Ho5+y4KxGgmjGKZypG/Ag/0223oIRVNzPe9GtpktSM0jwd9cMgzTa4/mpBbMLN0=
